### PR TITLE
Create and convert core stylesheet to SCSS

### PR DESCRIPTION
**Pull request by pqt**
Compiled using RubySASS, may get this working with Grunt Asset
Management in the future but it’s a start for now.

### CODE REVIEW

**Comment by pqt** [comment]
I don't know if you use SCSS or any other preprocessors for stylesheets, but it's a lot easier to manage, I also removed a few redundancies with classes where they repeated.

**Comment by seahorsepip** [comment]
The button colors aren't correct and the shadows aren't working anymore when I use this scss compared to the original css.

**Comment by seahorsepip** [comment]
Also //Overflow should be /\* Overflow _/ and the whole /_ScrollTop & ScrollBottom */ part needs to be added properly.

**Comment by pqt** [comment]
@seahorsepip alright, I'll take a look

> // Overflow should be /\* Overflow */

The double slash works as a proper comment in a preprocessor environment. Or do you want me to use slash-asterisk syntax just out of principal?

> The button colors aren't correct and the shadows aren't working anymore

I'll be testing this further today a little bit.

> whole ScrollTop & ScrollBottom part needs to be added properly.

What's not correct? I've added it [here](https://github.com/AustinPaquette/jPopup/commit/d658df27e2db4ec88085af4f6fd724a2bfca86ee#diff-27171bc415a775451f758b72529a66c2R271) incase you didn't notice it? I wanted to clean it up at some point afterwards as well.

**Comment by seahorsepip** [comment]
@AustinPaquette  Just use your css and my css in jsfiddle and compare the result, you'll see that  scrolling inside the popup is different and that my css has 1 grey, 1 red and 1 blue button and your css has 2 red and 1 blue button.

**Comment by seahorsepip** [comment]
Learned something new today :P

**Comment by seahorsepip** [comment]
The shadows on scroll are still not working like in the original css file(When popup content is too high for browser viewport it will show scroll shadows).

**Comment by pqt** [comment]
Realized the issue with the button and fixed in https://github.com/AustinPaquette/jPopup/commit/c82546880f577d5bb96714efc59982283983bf68

Just tackling the scrolling shadows now

**Comment by pqt** [comment]
Also, do you want to gitignore the `css` directory? It will avoid having the map file and minified sheet get committed every time, your call though.

**Comment by seahorsepip** [comment]
I'm not very experienced with git so I don't even know what the map file is about. Do what you think is best :smile:

**Comment by pqt** [comment]
It's an SCSS thing, not so much git. [Here's a quick post](http://thesassway.com/intermediate/using-source-maps-with-sass) I found that explains more about it's purpose.

If I ignore the css directory, then it removes the base CSS file(s) which would require you build/compile the scss file in some way before being able to properly use it.

**Comment by seahorsepip** [comment]
I'm not sure what's best. We need a jpopup.scss and a jpopup.min.css, it doesn't matter if the jpopup.min.css file needs to edited on every jpopup.scss edit.

**Comment by pqt** [comment]
I've fixed the box-shadow issue and updated the GitIgnore file to no longer include the CSS folder. You'll have to delete the files themselves from the repo though once this is merged.

**Comment by seahorsepip** [comment]
Seems everything is working properly now, merging pull request.

**Pull request merged**
